### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'   what():  basic_string::substr: __pos (which is 1) > this->size() (which is 0)

### ISSUE THREAD

**Issue by mazertwo** [mycroft/chainstate#10]
Hello, starmyc!

I add REDEN (https://github.com/RedenCore/Reden/blob/master/src/chainparams.cpp)

{ "reden",                  { 0x3c }, 1, { 0x10 }, 1 }, // Also uses 60, 16

But have error in cs.errors:

using obfuscation key 6ae3411e08c3ee64
Record type 14 is not handled.
Index: 0e006f62667573636174655f6b6579
Value: 086ae3411e08c3ee64

last block: 64eec3081c401b2fefce63148a8e8621edef23cac15154aa4d51a6714d95ddca

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 1) > this->size() (which is 0)

**Comment by mycroft** [comment]
Not planning to add other coins.
