### ISSUE TITLE
obfuscation key not found

### ISSUE THREAD

**Issue by ghost** [mycroft/chainstate#15]
at first i got this error

cat /tmp/cs.errors
chainstate: chainstate.cc:82: int main(int, char**): Assertion `status.ok()' failed

so i followed https://github.com/mycroft/chainstate/issues/7

and modified as per https://github.com/mycroft/chainstate/issues/7#issuecomment-423115600

re make and now i have 

cat /tmp/cs.errors
obfuscation key not found... Please check bitcoin's log and report if bitcoin's obfuscation key not 0000000000000000.

**Comment by githubvipuser** [comment]
I have the same problem

Have you solved your problem?

**Comment by githubvipuser** [comment]
@rawmaterials 
I have the same problem

Have you solved your problem

**Comment by githubvipuser** [comment]
@rawmaterials 
I have the same problem

Have you solved your problem?

**Comment by mycroft** [comment]
Please attach full bitcoin core's log to check the key & make sure to follow instructions to use the tool.

**Comment by githubvipuser** [comment]
@mycroft 
Is this ?
[debug.log](https://github.com/mycroft/chainstate/files/3297821/debug.log)

**Comment by mycroft** [comment]
Okay, I can see there is an obfuscation key set in debug.log; I can also see you set options.create_if_missing to true, which will create a database if not existing, leading to the 2nd error you saw. You don't want that.

In order to use this tool, you need to:
1/ Shutdown the bitcoin core client;
2/ copy the "chainstate" as "state" directory in the chainstate tool directory
3/ launch the "chainstate" tool. If you copied the directory correctly, it should work correctly.

**Comment by githubvipuser** [comment]
@mycroft 
Do I need to configure bitcoinconf and restart bitobi core?
I copied the directory and still got an error
![a](https://user-images.githubusercontent.com/44932825/59623035-bff8f880-9165-11e9-821c-8926360a1a29.JPG)

**Comment by githubvipuser** [comment]
@mycroft 
I recopied the directory but the result is the same

**Comment by githubvipuser** [comment]
@mycroft 
I recopied the directory but the result is the same

Can I change the source code to match the key?

Or make other changes

Please let me know. Thank you

**Comment by githubvipuser** [comment]
@mycroft 

What is the command to get all addresses and balance saved to file?

**Comment by mycroft** [comment]
You marked all your comments as resolved. I assume you find your error.
Can I now close this issue ?

**Comment by githubvipuser** [comment]
yes you can. thanks

Patrick MARIE <notifications@github.com> 于2019年6月18日周二 上午2:36写道：
