### ISSUE TITLE
project not compile

### ISSUE THREAD

**Issue by Kosteloos** [mycroft/chainstate#17]
hi i run make and this result : 

`thor@thor-OptiPlex-3050:~/chainstate$` make
rm -f chainstate chainstate.o hex.o varint.o pubkey.o
g++ -Wall -I. -Ilibbase58 -Isecp256k1/include -Ibech32/ref/c -std=c++0x -c -o chainstate.o chainstate.cc
g++ -Wall -I. -Ilibbase58 -Isecp256k1/include -Ibech32/ref/c -std=c++0x -c -o hex.o hex.cc
g++ -Wall -I. -Ilibbase58 -Isecp256k1/include -Ibech32/ref/c -std=c++0x -c -o varint.o varint.cc
g++ -Wall -I. -Ilibbase58 -Isecp256k1/include -Ibech32/ref/c -std=c++0x -c -o pubkey.o pubkey.cc
g++ -o chainstate chainstate.o hex.o varint.o pubkey.o -Lsecp256k1/.libs -lsecp256k1 -lcrypto -lleveldb -Llibbase58/.libs -lbase58 -Lbech32/ref/c -lbech32
//usr/local/lib/libleveldb.a(table_builder.o) : Dans la fonction « leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) » :
table_builder.cc:(.text+0x7f9) : référence indéfinie vers « snappy::MaxCompressedLength(unsigned long) »
table_builder.cc:(.text+0x826) : référence indéfinie vers « snappy::RawCompress(char const*, unsigned long, char*, unsigned long*) »
//usr/local/lib/libleveldb.a(port_posix.o) : Dans la fonction « leveldb::port::InitOnce(int*, void (*)()) » :
port_posix.cc:(.text+0x145) : référence indéfinie vers « pthread_once »
//usr/local/lib/libleveldb.a(format.o) : Dans la fonction « leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) » :
format.cc:(.text+0x43a) : référence indéfinie vers « snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*) »
format.cc:(.text+0x5c0) : référence indéfinie vers « snappy::RawUncompress(char const*, unsigned long, char*) »
//usr/local/lib/libleveldb.a(env_posix.o) : Dans la fonction « leveldb::(anonymous namespace)::PosixEnv::StartThread(void (*)(void*), void*) » :
env_posix.cc:(.text+0x5ab) : référence indéfinie vers « pthread_create »
//usr/local/lib/libleveldb.a(env_posix.o) : Dans la fonction « leveldb::(anonymous namespace)::PosixEnv::Schedule(void (*)(void*), void*) » :
env_posix.cc:(.text+0x863) : référence indéfinie vers « pthread_create »
//usr/local/lib/libleveldb.a(env_posix.o) : Dans la fonction « leveldb::Env::Default() » :
env_posix.cc:(.text+0x235f) : référence indéfinie vers « pthread_once »
collect2: error: ld returned 1 exit status
Makefile:11 : la recette pour la cible « chainstate » a échouée
make: *** [chainstate] Erreur 1

**Comment by mycroft** [comment]
Without more information about environment, libs installed, it is not really possible to help you.
You might notice your leveldb lacks some dependencies, like "snappy" or the libpthread. This is not a chainstate issue.

Thanks.
