### ISSUE TITLE
All balances

### ISSUE THREAD

**Issue by 2718281828459045** [mycroft/chainstate#2]
In your example the balance is output for one address 1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX. can make a balance output for all addresses?

**Comment by mycroft** [comment]
Thanks you for your interest.
Unfortunately, this project has for goal to provide some code to parse the chainstate, not compute all balances. This is something I get regularly asked about, and I do not wish to provide for free a way to dump all balances.
Cheers!
