### ISSUE TITLE
Dogecoin errors

### ISSUE THREAD

**Issue by mrx23dot** [mycroft/chainstate#24]
Doge coin gives a ton of these errors on stderr:

Record type 14 is not handled.
Index: 0e006f62667573636174655f6b6579
Value: 0846e28e656731bb91

last block: 95dec2ba0d190a6e65fbb569d8c1c1a39db94ed008ed818739bbf6aab3b1c30b

**ERROR type: o on TX:** 73e749cae7eb3221f83bc28e3e91b662a068b5d9b770775deb09820b71f80a00 | Version: 1
Value: 010e03096f512103c5268d1b2c69b032c4c00f0badb250fcb0991653998146676d120eb22677d8d721024221b6ce38c3810ca479fea0c3ecf44496d3cac7556375b8edc3c8ed8c6f550f2>
Remaining: 6f512103c5268d1b2c69b032c4c00f0badb250fcb0991653998146676d120eb22677d8d721024221b6ce38c3810ca479fea0c3ecf44496d3cac7556375b8edc3c8ed8c6f550f2103d>
**ERROR type: o on TX:** 621b36d7203d72ac6f1975a02712bcc491180b09b163e53ca35c784b0e612300 | Version: 1

1.6MB of these lines.

**Comment by mrx23dot** [comment]
Also decompression of amount seems to be off:
it outputs 
e0b5dc4f1e9c9c5362ca40018a68b9d540a8bcd8a2c55aa0c3ef8dec44ecffff;0;DGERWKwszbE1DSTYCpAd5fjrHz4tbXnCZ6;1500000000

explorer says:
https://blockchair.com/dogecoin/address/DGERWKwszbE1DSTYCpAd5fjrHz4tbXnCZ6
Balance 359.8288123 DOGE 50.64USD
Total received 359.8288123 DOGE 74.68USD
Total spent 0 DOGE

I dont see correlation, also multiplier is different for other addresses.

**Comment by mycroft** [comment]
Hey.
For the first comment:
Indeed. Those are lines that can not be decoded as acceptable transactions, and thus are stored in the txdb but just ignored. There are a lot of those in dogecoin, bitcoin or other coins and made part in the past of custom tests or third party implementations.
chainstate ignores those.

For the 2nd: The output file is a dump of available transactions that can be spent. For a single address, there can be multiple transactions. If you check e0b5dc4f1e9c9c5362ca40018a68b9d540a8bcd8a2c55aa0c3ef8dec44ecffff you'll see DGERWKwszbE1DSTYCpAd5fjrHz4tbXnCZ6 received 1500000000 in this transaction.

This address received another transaction:

$ grep DGERWKwszbE1DSTYCpAd5fjrHz4tbXnCZ6 chainstate.dogecoin.out
b82bdd2746e511c74bca108bf068118f8fde9929b74b907178bdaa66a1238db6;0;DGERWKwszbE1DSTYCpAd5fjrHz4tbXnCZ6;34482881230
e0b5dc4f1e9c9c5362ca40018a68b9d540a8bcd8a2c55aa0c3ef8dec44ecffff;0;DGERWKwszbE1DSTYCpAd5fjrHz4tbXnCZ6;1500000000

Regards

**Comment by mrx23dot** [comment]
Fare enough, thank you!

After I summed up utxos per address it seems to be correct.
