### ISSUE TITLE
Phore network

### ISSUE THREAD

**Issue by mrx23dot** [mycroft/chainstate#25]
I synced out the chainstate for Phore coin (~250MB), addresses seemed fully compatible with bitcoin. But running this on it gives Aborted error.

I can usually get away with similar networks to bitcoin, but not with this one.
Is it that different?
https://drive.google.com/file/d/1zowA4J9XLbZhYYMTf609P1EUWC7xrH7e/view?usp=sharing

**Comment by mycroft** [comment]
Hello, I took a look quickly and indeed, it seems like some internal changes were done to encode transactions a bit different. I can find the same existing addresses, but amounts are not matching explorer's. Therefore, it would require specific reverse engineering to make it work as it is for other coins.

**Comment by mrx23dot** [comment]
Thank you, I don't think it's worth the effort then.
