### ISSUE TITLE
Parsing litecoin -> terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by ant0n-n** [mycroft/chainstate#4]
Hi there

I am trying to parse the litecoin chainstate. I haven't downloaded the full blockchain yet, as I wanted to get this working before I start working through the full chain.

note* Parsing Bitcoin and Dashcore chainstate worked successfully for me.

I get the following in the error file when I run the following on the litecoin chainstate:
  time ./chainstate >/tmp/cs.out 2>/tmp/cs.err

cat /tmp/cs.err
Record type 14 is not handled.
Index: 0e006f62667573636174655f6b6579
Value: 085add9921d08be924

last block: 14bf5ffe0ebc17c441bea2e4ed171dd0efc44518eba5228f8b26b0c3b7f41a39

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 1) > this->size() (which is 0)
Aborted (core dumped)

Let me know if I can provide you with more information?

**Comment by mycroft** [comment]
I've tried with current chainstate of **litecoin 0.15.1** and fail to reproduce the error.
Could you tell me which **litecoin** version you're using? Also, post your **chainstate** directory somewhere online ? Thanks you.

**Comment by ant0n-n** [comment]
Litecoin Core version v0.14.2 (64-bit)
I will update to the latest version and let you know.

My chainstate directory is the same as master. If I don't come right with the updated litecoin I will upload my chainstate directory for you to have a look at.

**Comment by ant0n-n** [comment]
Updated Litecoin to v0.16.0
It parsed correctly. 

Thanks for the help!
