### ISSUE TITLE
aborting with error

### ISSUE THREAD

**Issue by uFire** [mycroft/chainstate#7]
Hi @mycroft 

I have installed the chainstate without errors/warnings but it won't run. 

```
[xuser@power chainstate]$ time ./chainstate >/tmp/cs.output 2>/tmp/cs.errors
Aborted

real    0m0.024s
user    0m0.014s
sys     0m0.004s
[xuser@power chainstate]$
```

And I am getting 
```
[xuser@power chainstate]$ cat /tmp/cs.errors
chainstate: chainstate.cc:82: int main(int, char**): Assertion `status.ok()' failed.
[xuser@power chainstate]$
```

CentOS 7 x64
LevelDB 1.12.0 (installed via yum from epel repo)

Any ideas? 

Thanks in advance :)

**Comment by peymanfr** [comment]
I have exactly the same problem
Aborted (core dumped)
It seems program have problem  with bitcoin 0.16 client.

**Comment by ghost** [comment]
Same here : Ubuntu 16.04 x64, LevelDB 1.12.0

```chainstate: chainstate.cc:82: int main(int, char**): Assertion `status.ok()' failed.
Aborted (core dumped)```

**Comment by morarity** [comment]
Same issue.

My Box: Ubuntu 14.04 x64.

`chainstate: chainstate.cc:82: int main(int, char**): Assertion `status.ok()' failed. Aborted (core dumped)`

**Comment by Innominatam** [comment]
Just take levelDB lib from bitcoin-core https://github.com/bitcoin/bitcoin/tree/master/src/leveldb/include.

**Comment by Muncan90** [comment]
Same issue here: Ubuntu 16.04 x64, LevelDB 1.20

@Maxon-ik could you elaborate on your suggestion to take the levelDB lib from bitcoin-core please?

**Comment by Pakshin** [comment]
Hi guys. I have the same problem, who has found the solution?
Downgrade Bitcoin Core can help?

**Comment by Muncan90** [comment]
**Update**

I was able to resolve the below error message by making some minor changes to chainstate.cc before building with make
```
chainstate: chainstate.cc:82: int main(int, char**): Assertion `status.ok()' failed.
```

**Steps**
Open chainstate.cc with your preferred text editor.


Change line 40 from
```c++
options.create_if_missing = false;
```
to
```c++
options.create_if_missing = true;
```
___
Change line 81 from
```c++
leveldb::Status status = leveldb::DB::Open(options, "state", &db);
```
to
```c++
leveldb::Status status = leveldb::DB::Open(options, "./state", &db);
```

Then follow the normal build instructions using make
___

I tested this configuration using a chainstate export from last night and validated the results with success, balances were accurate.

The only issue I observed was cosmetic, high balances are formatted in scientific notation (extract of my export below)

```
16ftSEQ4ctQFDtVZiUBusQUjRrGhM3JYwe;1.68791e+13
3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r;1.65583e+13
16rCmCmbuWDhPjWTrpQGaU3EPdZF7MTdUk;1.07203e+13
3Cbq7aT1tY8kMxWLbitaG7yT6bPbKChq64;9.80425e+12
3Nxwenay9Z8Lc9JBiywExpnEFiLp6Afp8v;9.78483e+12
183hmJGRuTEi2YDCWy5iozY8rZtFwVgahM;8.59472e+12
```

Can anyone else test this and confirm your results?

**Comment by Pakshin** [comment]
Yes, it worked. Many thanks!

**Comment by PsyShark** [comment]
I performed all the above manipulations, but the error persists (chainstate: chainstate.cc:82: int main(int, char**): Assertion `status.ok()' failed.). What other options can you try?

**Comment by Muncan90** [comment]
Added pull request #14

**Comment by ghost** [comment]
i followed this and now i have 

obfuscation key not found... Please check bitcoin's log and report if bitcoin's obfuscation key not 0000000000000000.
